# -*- coding: utf-8 -*-
"""Course recommendation system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVO8imqZtuzMUJA4ZEdmBFIexLpaXJRK
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

data=pd.read_csv("/content/Coursera.csv")

data.head()

data.info()

data.columns

data_features=data[['Course Name', 'University', 'Difficulty Level', 'Course URL', 'Course Description']]
data_features.shape

x=data_features['Course Name']+' '+data_features['University']+' '+data_features['Difficulty Level']+' '+data_features['Course URL']+' '+data_features['Course Description']
x

from sklearn.feature_extraction.text import TfidfVectorizer
tdidf=TfidfVectorizer()
x=tdidf.fit_transform(x)

"""# **Finding the score**"""

from sklearn.metrics.pairwise import cosine_similarity
cossim=cosine_similarity(x)
cossim

"""# **Get input and recommend user**"""

course_name=input("Enter the course name : ")

course_list=data['Course Name'].tolist()

import difflib
course_recommendation=difflib.get_close_matches(course_name,course_list,n=5)
print(course_recommendation)

print("No.\tCourse Name\t\t\t\tCourse Url")
for i in range(0,len(course_recommendation)):
    url=data[data['Course Name']==course_recommendation[i]]['Course URL'].values[0]
    print((i+1),"\t",course_recommendation[i],"\t\t\t",url)
